import React,{useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';

function PasswordField({autoComplete}){
  const [visible,setVisible]=useState(false);
  return <div className="password-field"><input name="password" type={visible?'text':'password'} autoComplete={autoComplete} minLength="8" maxLength="72" required placeholder="At least 8 characters"/><button type="button" className="password-toggle" aria-label={visible?'Hide password':'Show password'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>{visible&&<path d="m4 4 16 16"/>}</svg></button></div>
}

export function AuthFlow({mode,api,onAuth}){
  const navigate=useNavigate();
  const [error,setError]=useState(''),[busy,setBusy]=useState(false);
  async function submit(event){event.preventDefault();setBusy(true);setError('');const body=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});onAuth(result);navigate('/dashboard',{replace:true})}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <main className="auth-wrap"><div className="auth-aside"><span className="eyebrow">CAMPUSSHARE · RENT &amp; REUSE</span><h1>Good things<br/>find their way<br/><em>around.</em></h1><p>Borrow what you need. Rent what you don't. Share what you have.</p></div><form className="auth-card" onSubmit={submit}><span className="eyebrow">{mode==='login'?'WELCOME BACK':'JOIN YOUR CAMPUS'}</span><h2>{mode==='login'?'Sign in':'Create your account'}</h2><p>{mode==='login'?'Pick up where your community left off.':'Start sharing with students on your campus.'}</p>{mode==='register'&&<><label>Your name<input name="name" required minLength="2" maxLength="120" autoComplete="name" placeholder="Your name"/></label><label>College or campus<input name="college" required minLength="2" maxLength="160" autoComplete="organization" placeholder="Your college or university"/></label><label>Department <span className="optional">optional</span><input name="department" maxLength="160" placeholder="Your department"/></label></>}<label>Campus email<input name="email" type="email" required maxLength="255" autoComplete="email" placeholder="you@college.edu"/></label><label>Password<PasswordField autoComplete={mode==='login'?'current-password':'new-password'}/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="button full" disabled={busy}>{busy?(mode==='login'?'Signing in…':'Creating account…'):mode==='login'?'Sign In':'Create Account'}</button><div className="auth-switch">{mode==='login'?<>New around here? <Link to="/register">Create an account</Link></>:<>Already a member? <Link to="/login">Sign in</Link></>}</div></form></main>
}
