import React,{useEffect,useRef,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';

function EyedPassword({name='password',autoComplete='current-password',value,onChange,required=true}){
  const [visible,setVisible]=useState(false);
  return <div className="password-field"><input name={name} type={visible?'text':'password'} autoComplete={autoComplete} minLength="8" maxLength="72" required={required} value={value} onChange={onChange} placeholder="At least 8 characters"/><button type="button" className="password-toggle" aria-label={visible?'Hide password':'Show password'} aria-pressed={visible} onClick={()=>setVisible(v=>!v)}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s3.6-7 10-7 10 7 10 7-3.6 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/>{visible&&<path d="m4 4 16 16"/>}</svg></button></div>
}

function Waiting({type,challengeId,api,onBack}){
  const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  const approval=type==='loginApproval';
  async function resend(){setBusy(true);setMessage('');try{const endpoint=approval?'/auth/approval/resend':'/auth/verification/resend';const result=await api(endpoint,{method:'POST',body:JSON.stringify({challengeId})});setMessage(result.message||'If the request is still valid, a new email link has been sent.')}catch(error){setMessage(error.message)}finally{setBusy(false)}}
  return <section className="auth-card auth-waiting" aria-live="polite"><span className="eyebrow">CAMPUSSHARE SECURITY</span><div className="auth-mail-icon" aria-hidden="true">✉</div><h2>Please check your email</h2><p>{approval?'We’ve sent an approval link to your registered email address. Open it and click “Approve Login” to continue to CampusShare.':'We’ve sent a verification link to your email address. Click “Verify Email” to activate your CampusShare account.'}</p>{message&&<div className="notice-inline">{message}</div>}<button className="button full" type="button" disabled={busy||!challengeId} onClick={resend}>{busy?'Sending email…':approval?'Resend approval email':'Resend verification email'}</button><button className="quiet-button auth-back" type="button" onClick={onBack}>{approval?'Back to Login':'Back to Sign In'}</button></section>
}

export function AuthFlow({mode,api,onAuth}){
  const navigate=useNavigate();
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[pending,setPending]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem('campusshare-pending-auth')||'null');return saved?.mode===mode?saved:null}catch{return null}});
  function startWaiting(type,challengeId){const next={mode,type,challengeId};sessionStorage.setItem('campusshare-pending-auth',JSON.stringify(next));setPending(next)}
  function back(){sessionStorage.removeItem('campusshare-pending-auth');setPending(null);navigate('/login')}
  async function submit(event){event.preventDefault();setBusy(true);setError('');const body=Object.fromEntries(new FormData(event.currentTarget));try{const result=await api(`/auth/${mode}`,{method:'POST',body:JSON.stringify(body)});startWaiting(result.approvalRequired?'loginApproval':'emailVerification',result.challengeId)}catch(err){if(err.challengeId&&mode==='register')startWaiting('emailVerification',err.challengeId);else setError(err.message)}finally{setBusy(false)}}
  return <main className="auth-wrap"><div className="auth-aside"><span className="eyebrow">YOUR CAMPUS, SHARED</span><h1>Good things<br/>find their way<br/><em>around.</em></h1><p>A community is made by what we share.</p><span className="auth-doodle">✳</span></div>{pending?<Waiting type={pending.type} challengeId={pending.challengeId} api={api} onBack={back}/>:<form className="auth-card" onSubmit={submit}><span className="eyebrow">{mode==='login'?'WELCOME BACK':'COME ON IN'}</span><h2>{mode==='login'?'Sign in':'Create your account'}</h2><p>{mode==='login'?'Pick up where your community left off.':'Start sharing with students on your campus.'}</p>{mode==='register'&&<label>Your name<input name="name" required minLength="2" maxLength="120" autoComplete="name" placeholder="How should we call you?"/></label>}<label>Campus email<input name="email" type="email" required maxLength="255" autoComplete="email" placeholder="you@college.edu"/></label><label>Password<EyedPassword autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode==='register'&&<label>College <span className="optional">optional</span><input name="college" maxLength="160" placeholder="Your college or university"/></label>}{error&&<div className="error" role="alert">{error}</div>}<button className="button full" disabled={busy}>{busy?(mode==='login'?'Sending approval email…':'Creating account…'):mode==='login'?'Continue to email approval':'Create account'}</button>{mode==='login'&&<Link className="forgot-link" to="/forgot-password">Forgot password?</Link>}<div className="auth-switch">{mode==='login'?<>New around here? <Link to="/register">Create an account</Link></>:<>Already a member? <Link to="/login">Sign in</Link></>}</div></form>}</main>
}

export function AuthAction({type,api,onAuth}){
  const navigate=useNavigate(),once=useRef(false),[state,setState]=useState('checking'),[error,setError]=useState(''),[challengeId,setChallengeId]=useState('');
  const params=new URLSearchParams(window.location.hash.slice(1));
  const token=params.get('token')||'',challenge=params.get('challenge')||'';
  useEffect(()=>{if(once.current)return;once.current=true;setChallengeId(challenge);if(!token){setState('invalid');return}const endpoint=type==='approval'?'/auth/approval/approve':'/auth/verification/verify';api(endpoint,{method:'POST',body:JSON.stringify({token})}).then(result=>{sessionStorage.removeItem('campusshare-pending-auth');onAuth(result);setState('success');navigate('/dashboard',{replace:true})}).catch(err=>{setError(err.message);setState(err.code==='LINK_EXPIRED'?'expired':err.code==='LINK_USED'?'used':'invalid')})},[api,challenge,navigate,onAuth,token,type]);
  const resendView=state==='expired'&&challengeId;
  return <main className="auth-wrap"><div className="auth-aside"><span className="eyebrow">CAMPUSSHARE SECURITY</span><h1>{type==='approval'?'Approve your':'Verify your'}<br/><em>email link.</em></h1><p>Secure links keep your CampusShare account protected.</p></div><section className="auth-card auth-waiting" aria-live="polite">{state==='checking'?<><span className="eyebrow">SECURE LINK</span><h2>Checking your link…</h2><p>Please wait while CampusShare verifies it.</p></>:state==='success'?<><h2>Email confirmed</h2><p>Opening your CampusShare account…</p></>:state==='expired'?<><span className="eyebrow">LINK EXPIRED</span><h2>Verification link expired.</h2><p>Please request a new {type==='approval'?'approval':'verification'} link.</p>{resendView&&<Waiting type={type==='approval'?'loginApproval':'emailVerification'} challengeId={challengeId} api={api} onBack={()=>navigate('/login')}/>}</>:state==='used'?<><span className="eyebrow">LINK ALREADY USED</span><h2>This verification link has already been used.</h2><p>For your security, a used link cannot start another session.</p><Link className="button full" to="/login">Back to Login</Link></>:<><span className="eyebrow">LINK UNAVAILABLE</span><h2>This link can’t be used.</h2><p>{error||'Request a new link or return to sign in.'}</p><Link className="button full" to="/login">Back to Login</Link></>}</section></main>
}

export function ForgotPassword({api}){
  const [email,setEmail]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false),[error,setError]=useState('');
  async function submit(event){event.preventDefault();setBusy(true);setError('');try{await api('/auth/password/forgot',{method:'POST',body:JSON.stringify({email})});setSent(true)}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <main className="auth-wrap"><div className="auth-aside"><span className="eyebrow">ACCOUNT ACCESS</span><h1>Find your way<br/><em>back in.</em></h1><p>We’ll email a secure password reset link if an active account matches.</p></div><form className="auth-card" onSubmit={submit}><span className="eyebrow">PASSWORD RESET</span><h2>{sent?'Check your inbox':'Forgot password?'}</h2><p>{sent?'If an active account matches that address, a reset link is on its way.':'Enter your CampusShare email address to request a reset link.'}</p>{!sent&&<><label>Campus email<input type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} required maxLength="255"/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="button full" disabled={busy}>{busy?'Sending reset link…':'Send reset link'}</button></>}<div className="auth-switch"><Link to="/login">Back to Sign In</Link></div></form></main>
}

export function ResetPassword({api}){
  const navigate=useNavigate(),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[done,setDone]=useState(false);
  const token=new URLSearchParams(window.location.hash.slice(1)).get('token')||'';
  async function submit(event){event.preventDefault();setError('');if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);try{await api('/auth/password/reset',{method:'POST',body:JSON.stringify({token,password})});setDone(true)}catch(err){setError(err.message)}finally{setBusy(false)}}
  return <main className="auth-wrap"><div className="auth-aside"><span className="eyebrow">ACCOUNT ACCESS</span><h1>Choose a new<br/><em>password.</em></h1><p>Use a password you have not used on another account.</p></div><form className="auth-card" onSubmit={submit}><span className="eyebrow">PASSWORD RESET</span><h2>{done?'Password updated':token?'Set a new password':'Reset link unavailable'}</h2>{done?<><p>Your password has been updated. Sign in with the new password.</p><button type="button" className="button full" onClick={()=>navigate('/login')}>Go to Sign In</button></>:!token?<><p>This link is invalid or missing. Request a new password reset link.</p><Link className="button full" to="/forgot-password">Request a new link</Link></>:<><p>Choose a new password for your CampusShare account.</p><label>New password<EyedPassword name="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/></label><label>Confirm password<EyedPassword name="confirm" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="button full" disabled={busy}>{busy?'Updating password…':'Update password'}</button></>}</form></main>
}
