const express = require('express');
const bcrypt = require('bcryptjs');
const { pool } = require('../config/database');
const { auth, admin, sign } = require('../middleware/auth');
const router = express.Router();
const asyncRoute = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const fail = (message, status=400) => Object.assign(new Error(message), { status });
const emailRE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
const itemFields = `i.id,i.owner_id,i.category_id,i.title,i.description,i.condition,i.type,i.status,i.location,i.created_at,u.name AS owner_name,c.name AS category,COALESCE((SELECT image_url FROM item_images im WHERE im.item_id=i.id ORDER BY created_at LIMIT 1),'') AS image_url`;

router.post('/auth/register', asyncRoute(async (req,res) => {
  const {name,email,password,college,department,year,hostel}=req.body||{};
  if(!name||name.trim().length<2||name.length>120) throw fail('Name must be between 2 and 120 characters.');
  if(!emailRE.test(email||'')||email.length>255) throw fail('Enter a valid email address.');
  if(typeof password!=='string'||password.length<8||password.length>72) throw fail('Password must be 8–72 characters.');
  if(year!==undefined&&year!==null&&(!Number.isInteger(Number(year))||Number(year)<1||Number(year)>6)) throw fail('Year must be between 1 and 6.');
  const hash=await bcrypt.hash(password,12);
  try { const {rows}=await pool.query('INSERT INTO users(name,email,password_hash,college,department,year,hostel) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,name,email,college,department,year,hostel,role,status',[name.trim(),email.trim().toLowerCase(),hash,college||null,department||null,year||null,hostel||null]); const user=rows[0]; res.status(201).json({user,token:sign(user)}); }
  catch(e){if(e.code==='23505') throw fail('An account with this email already exists.',409); throw e;}
}));
router.post('/auth/login', asyncRoute(async(req,res)=>{const {email,password}=req.body||{};if(!emailRE.test(email||'')||typeof password!=='string') throw fail('Enter your email and password.');const {rows}=await pool.query('SELECT id,name,email,password_hash,college,department,year,hostel,role,status FROM users WHERE email=$1',[email.toLowerCase()]);const u=rows[0];if(!u||!(await bcrypt.compare(password,u.password_hash))||u.status!=='active')throw fail('Email or password is incorrect.',401);delete u.password_hash;res.json({user:u,token:sign(u)});}));
router.get('/auth/me',auth,(req,res)=>res.json({user:req.user}));
router.get('/categories',asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT id,name,description FROM categories ORDER BY name');res.json(rows);}));
router.get('/items',asyncRoute(async(req,res)=>{const {q='',category='',type='',condition='',page='1'}=req.query;const p=Math.max(1,parseInt(page,10)||1);const values=[];const where=["i.status='available'"];if(q){values.push(`%${String(q).slice(0,100)}%`);where.push(`(i.title ILIKE $${values.length} OR i.description ILIKE $${values.length} OR i.location ILIKE $${values.length})`);}if(category){values.push(category);where.push(`i.category_id=$${values.length}`);}if(['lend','donate','exchange'].includes(type)){values.push(type);where.push(`i.type=$${values.length}`);}if(['new','like_new','good','used'].includes(condition)){values.push(condition);where.push(`i.condition=$${values.length}`);}const count=await pool.query(`SELECT COUNT(*)::int total FROM items i WHERE ${where.join(' AND ')}`,values);values.push(24,(p-1)*24);const {rows}=await pool.query(`SELECT ${itemFields} FROM items i JOIN users u ON u.id=i.owner_id LEFT JOIN categories c ON c.id=i.category_id WHERE ${where.join(' AND ')} ORDER BY i.created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);res.json({items:rows,total:count.rows[0].total,page:p});}));
router.get('/items/:id',asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT ${itemFields} FROM items i JOIN users u ON u.id=i.owner_id LEFT JOIN categories c ON c.id=i.category_id WHERE i.id=$1`,[req.params.id]);if(!rows[0])throw fail('Item not found.',404);res.json(rows[0]);}));
router.post('/items',auth,asyncRoute(async(req,res)=>{const {title,description,category_id,condition,type,location,image_url}=req.body||{};if(!title||title.trim().length>160||!description||description.trim().length>5000)throw fail('Add a title and description within the stated limits.');if(!['new','like_new','good','used'].includes(condition)||!['lend','donate','exchange'].includes(type))throw fail('Choose a valid condition and sharing type.');const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('INSERT INTO items(owner_id,category_id,title,description,condition,type,location) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[req.user.id,category_id||null,title.trim(),description.trim(),condition,type,location||null]);if(image_url&&/^https:\/\//i.test(image_url))await client.query('INSERT INTO item_images(item_id,image_url) VALUES($1,$2)',[rows[0].id,image_url]);await client.query('COMMIT');res.status(201).json({id:rows[0].id});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.patch('/items/:id',auth,asyncRoute(async(req,res)=>{const {title,description,condition,type,location,status}=req.body||{};const {rows}=await pool.query(`UPDATE items SET title=COALESCE($1,title),description=COALESCE($2,description),condition=COALESCE($3,condition),type=COALESCE($4,type),location=COALESCE($5,location),status=COALESCE($6,status),updated_at=NOW() WHERE id=$7 AND owner_id=$8 RETURNING id`,[title||null,description||null,condition||null,type||null,location||null,status||null,req.params.id,req.user.id]);if(!rows[0])throw fail('Item not found or you do not own it.',404);res.json({success:true});}));
router.delete('/items/:id',auth,asyncRoute(async(req,res)=>{const {rowCount}=await pool.query('DELETE FROM items WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.id]);if(!rowCount)throw fail('Item not found or you do not own it.',404);res.status(204).end();}));
router.get('/items/mine/list',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT ${itemFields} FROM items i JOIN users u ON u.id=i.owner_id LEFT JOIN categories c ON c.id=i.category_id WHERE i.owner_id=$1 ORDER BY i.created_at DESC`,[req.user.id]);res.json(rows);}));
router.post('/requests',auth,asyncRoute(async(req,res)=>{const {item_id,message}=req.body||{};if(!item_id||typeof message!=='string'||message.trim().length<5||message.length>1000)throw fail('Add a request message (5–1000 characters).');const client=await pool.connect();try{await client.query('BEGIN');const item=await client.query("SELECT id,owner_id FROM items WHERE id=$1 AND status='available' FOR UPDATE",[item_id]);if(!item.rows[0])throw fail('This item is no longer available.',409);if(item.rows[0].owner_id===req.user.id)throw fail('You cannot request your own item.');const {rows}=await client.query('INSERT INTO requests(item_id,requester_id,owner_id,message) VALUES($1,$2,$3,$4) RETURNING id',[item_id,req.user.id,item.rows[0].owner_id,message.trim()]);await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'request','New item request',$2)",[item.rows[0].owner_id,`${req.user.name} requested your item.`]);await client.query('COMMIT');res.status(201).json({id:rows[0].id});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.get('/requests',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT r.*,i.title,item_owner.name AS owner_name,requester.name AS requester_name FROM requests r JOIN items i ON i.id=r.item_id JOIN users item_owner ON item_owner.id=r.owner_id JOIN users requester ON requester.id=r.requester_id WHERE r.owner_id=$1 OR r.requester_id=$1 ORDER BY r.requested_at DESC`,[req.user.id]);res.json(rows);}));
router.patch('/requests/:id',auth,asyncRoute(async(req,res)=>{const {status,expected_return_date}=req.body||{};if(!['accepted','rejected','cancelled'].includes(status))throw fail('Choose accepted, rejected, or cancelled.');const client=await pool.connect();try{await client.query('BEGIN');const found=await client.query('SELECT * FROM requests WHERE id=$1 FOR UPDATE',[req.params.id]);const r=found.rows[0];if(!r)throw fail('Request not found.',404);if((status==='accepted'||status==='rejected')&&r.owner_id!==req.user.id)throw fail('Only the item owner can respond.',403);if(status==='cancelled'&&r.requester_id!==req.user.id)throw fail('Only the requester can cancel.',403);if(r.status!=='pending')throw fail('This request has already been resolved.',409);await client.query('UPDATE requests SET status=$1,responded_at=NOW() WHERE id=$2',[status,r.id]);if(status==='accepted'){await client.query("UPDATE items SET status='shared',updated_at=NOW() WHERE id=$1",[r.item_id]);await client.query('INSERT INTO transactions(item_id,owner_id,borrower_id,request_id,expected_return_date) VALUES($1,$2,$3,$4,$5)',[r.item_id,r.owner_id,r.requester_id,r.id,expected_return_date||null]);await client.query("UPDATE requests SET status='rejected',responded_at=NOW() WHERE item_id=$1 AND id<>$2 AND status='pending'",[r.item_id,r.id]);}await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'request_update','Request updated',$2)",[status==='cancelled'?r.owner_id:r.requester_id,`Your request was ${status}.`]);await client.query('COMMIT');res.json({success:true});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.get('/transactions',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT t.*,i.title,owner.name AS owner_name,borrower.name AS borrower_name FROM transactions t JOIN items i ON i.id=t.item_id JOIN users owner ON owner.id=t.owner_id JOIN users borrower ON borrower.id=t.borrower_id WHERE t.owner_id=$1 OR t.borrower_id=$1 ORDER BY t.started_at DESC`,[req.user.id]);res.json(rows);}));
router.patch('/transactions/:id/return',auth,asyncRoute(async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM transactions WHERE id=$1 FOR UPDATE',[req.params.id]);const t=rows[0];if(!t)throw fail('Transaction not found.',404);if(t.owner_id!==req.user.id&&t.borrower_id!==req.user.id)throw fail('Access denied.',403);if(t.status!=='active')throw fail('Transaction is already closed.',409);await client.query("UPDATE transactions SET status='returned',returned_at=NOW() WHERE id=$1",[t.id]);await client.query("UPDATE items SET status='available',updated_at=NOW() WHERE id=$1",[t.item_id]);await client.query('COMMIT');res.json({success:true});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.get('/notifications',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50',[req.user.id]);res.json(rows);}));
router.patch('/notifications/read',auth,asyncRoute(async(req,res)=>{await pool.query('UPDATE notifications SET is_read=true WHERE user_id=$1',[req.user.id]);res.json({success:true});}));
router.post('/reports',auth,asyncRoute(async(req,res)=>{const {reported_user_id,reported_item_id,reason,description}=req.body||{};if(typeof reason!=='string'||reason.trim().length<3||reason.length>120)throw fail('Provide a reason for this report.');const {rows}=await pool.query('INSERT INTO reports(reporter_id,reported_user_id,reported_item_id,reason,description) VALUES($1,$2,$3,$4,$5) RETURNING id',[req.user.id,reported_user_id||null,reported_item_id||null,reason.trim(),(description||'').slice(0,2000)]);res.status(201).json({id:rows[0].id});}));
router.get('/admin/reports',auth,admin,asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT r.*,u.name AS reporter_name FROM reports r JOIN users u ON u.id=r.reporter_id ORDER BY r.created_at DESC');res.json(rows);}));
router.patch('/admin/reports/:id',auth,admin,asyncRoute(async(req,res)=>{const {status}=req.body||{};if(!['reviewing','resolved','dismissed','open'].includes(status))throw fail('Invalid report status.');const {rowCount}=await pool.query('UPDATE reports SET status=$1,resolved_at=CASE WHEN $1 IN (\'resolved\',\'dismissed\') THEN NOW() ELSE NULL END WHERE id=$2',[status,req.params.id]);if(!rowCount)throw fail('Report not found.',404);res.json({success:true});}));
router.get('/admin/users',auth,admin,asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT id,name,email,college,role,status,created_at FROM users ORDER BY created_at DESC LIMIT 500');res.json(rows);}));
router.patch('/admin/users/:id/status',auth,admin,asyncRoute(async(req,res)=>{const {status}=req.body||{};if(!['active','suspended'].includes(status))throw fail('Invalid account status.');if(req.params.id===req.user.id&&status==='suspended')throw fail('You cannot suspend your own account.');const {rowCount}=await pool.query('UPDATE users SET status=$1,updated_at=NOW() WHERE id=$2',[status,req.params.id]);if(!rowCount)throw fail('User not found.',404);res.json({success:true});}));
module.exports=router;
