const express = require('express');
const { pool } = require('../config/database');
const { auth, admin } = require('../middleware/auth');
const router = express.Router();
const asyncRoute = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
const fail = (message, status=400, code) => Object.assign(new Error(message), { status, ...(code ? { code } : {}) });
const validUUID = value => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const validISODate = value => typeof value==='string' && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`)) && new Date(`${value}T00:00:00Z`).toISOString().slice(0,10)===value;
const itemFields = `i.id,i.owner_id,i.category_id,i.title,i.description,i.condition,i.type,i.status,i.location,i.created_at,i.price_per_day,i.available_from,i.available_until,u.name AS owner_name,u.college AS owner_college,c.name AS category,COALESCE((SELECT image_url FROM item_images im WHERE im.item_id=i.id ORDER BY created_at LIMIT 1),'') AS image_url,COALESCE((SELECT AVG(rating)::numeric(3,2) FROM reviews WHERE reviewee_id=u.id),0) AS owner_rating,COALESCE((SELECT COUNT(*)::int FROM reviews WHERE reviewee_id=u.id),0) AS owner_review_count`;

router.get('/favorites',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT ${itemFields} FROM favorites f JOIN items i ON i.id=f.item_id JOIN users u ON u.id=i.owner_id LEFT JOIN categories c ON c.id=i.category_id WHERE f.user_id=$1 ORDER BY f.created_at DESC`,[req.user.id]);res.json(rows);}));
router.post('/favorites/:itemId',auth,asyncRoute(async(req,res)=>{if(!validUUID(req.params.itemId))throw fail('Item not found.',404,'ITEM_NOT_FOUND');const exists=await pool.query('SELECT id FROM items WHERE id=$1',[req.params.itemId]);if(!exists.rowCount)throw fail('Item not found.',404,'ITEM_NOT_FOUND');await pool.query('INSERT INTO favorites(user_id,item_id) VALUES($1,$2) ON CONFLICT(user_id,item_id) DO NOTHING',[req.user.id,req.params.itemId]);res.status(201).json({success:true});}));
router.delete('/favorites/:itemId',auth,asyncRoute(async(req,res)=>{if(!validUUID(req.params.itemId))throw fail('Item not found.',404,'ITEM_NOT_FOUND');await pool.query('DELETE FROM favorites WHERE user_id=$1 AND item_id=$2',[req.user.id,req.params.itemId]);res.status(204).end();}));router.get('/categories',asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT id,name,description FROM categories ORDER BY name');res.json(rows);}));
router.get('/items',asyncRoute(async(req,res)=>{
 const {q='',category='',type='',condition='',location='',page='1',availability='available',max_price}=req.query;
 const p=Math.max(1,parseInt(page,10)||1),values=[],where=[];
 if(availability!=='all')where.push("i.status='available' AND (i.available_from IS NULL OR i.available_from <= CURRENT_DATE) AND (i.available_until IS NULL OR i.available_until >= CURRENT_DATE)");
 if(q){values.push(`%${String(q).slice(0,100)}%`);where.push(`(i.title ILIKE $${values.length} OR i.description ILIKE $${values.length} OR i.location ILIKE $${values.length})`);}
 if(location){values.push(`%${String(location).slice(0,100)}%`);where.push(`i.location ILIKE $${values.length}`);}
 if(category){values.push(category);where.push(`i.category_id=$${values.length}`);}
 if(['lend','donate','exchange','borrow','rent','both'].includes(type)){values.push(type);where.push(`i.type=$${values.length}`);}
 if(['new','like_new','good','used'].includes(condition)){values.push(condition);where.push(`i.condition=$${values.length}`);}
 if(max_price!==undefined&&max_price!==''){const price=Number(max_price);if(!Number.isFinite(price)||price<0)throw fail('Enter a valid maximum price.');values.push(price);where.push(`(i.price_per_day IS NULL OR i.price_per_day <= $${values.length})`);}
 const clause=where.length?`WHERE ${where.join(' AND ')}`:'';
 const count=await pool.query(`SELECT COUNT(*)::int total FROM items i ${clause}`,values);
 values.push(24,(p-1)*24);
 const {rows}=await pool.query(`SELECT ${itemFields} FROM items i JOIN users u ON u.id=i.owner_id LEFT JOIN categories c ON c.id=i.category_id ${clause} ORDER BY i.created_at DESC LIMIT $${values.length-1} OFFSET $${values.length}`,values);
 res.json({items:rows,total:count.rows[0].total,page:p});
}));router.get('/items/:id',asyncRoute(async(req,res)=>{if(!validUUID(req.params.id))throw fail('Item not found.',404,'ITEM_NOT_FOUND');const {rows}=await pool.query(`SELECT ${itemFields} FROM items i JOIN users u ON u.id=i.owner_id LEFT JOIN categories c ON c.id=i.category_id WHERE i.id=$1`,[req.params.id]);if(!rows[0])throw fail('Item not found.',404,'ITEM_NOT_FOUND');res.json(rows[0]);}));
router.get('/items/:id/inquiry',auth,asyncRoute(async(req,res)=>{if(!validUUID(req.params.id))return res.json({inquiry:null});const {rows}=await pool.query('SELECT id FROM item_inquiries WHERE item_id=$1 AND requester_id=$2',[req.params.id,req.user.id]);res.json({inquiry:rows[0]||null});}));
router.post('/items/:id/inquiries',auth,asyncRoute(async(req,res)=>{const body=typeof req.body?.body==='string'?req.body.body.trim():'';if(body.length<1||body.length>2000)throw fail('Message must be between 1 and 2,000 characters.');if(!validUUID(req.params.id))throw fail('Item not found.',404,'ITEM_NOT_FOUND');const client=await pool.connect();try{await client.query('BEGIN');const item=await client.query("SELECT id,owner_id,title FROM items WHERE id=$1 AND status='available' FOR SHARE",[req.params.id]);if(!item.rows[0])throw fail('Item not found or is no longer available.',404,'ITEM_NOT_FOUND');if(item.rows[0].owner_id===req.user.id)throw fail('You cannot message yourself about your own item.',403);const inquiry=await client.query('INSERT INTO item_inquiries(item_id,requester_id,owner_id) VALUES($1,$2,$3) ON CONFLICT(item_id,requester_id) DO UPDATE SET owner_id=EXCLUDED.owner_id RETURNING id',[req.params.id,req.user.id,item.rows[0].owner_id]);const message=await client.query('INSERT INTO messages(inquiry_id,sender_id,recipient_id,body) VALUES($1,$2,$3,$4) RETURNING id,sender_id,recipient_id,body,created_at',[inquiry.rows[0].id,req.user.id,item.rows[0].owner_id,body]);await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'message','New item message',$2)",[item.rows[0].owner_id,`${req.user.name} sent a message about ${item.rows[0].title}.`]);await client.query('COMMIT');res.status(201).json({inquiry_id:inquiry.rows[0].id,message:message.rows[0]});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.post('/items',auth,asyncRoute(async(req,res)=>{const {title,description,category_id,condition,type,location,image_url,price_per_day,available_from,available_until}=req.body||{};if(typeof title!=='string'||title.trim().length<2||title.trim().length>160||typeof description!=='string'||description.trim().length<5||description.trim().length>5000)throw fail('Add a title and description within the stated limits.');if(!['new','like_new','good','used'].includes(condition)||!['borrow','rent','both'].includes(type))throw fail('Choose a valid condition and sharing type.');const submittedPrice=price_per_day===''||price_per_day==null?null:Number(price_per_day);if(type==='rent'&&(!Number.isFinite(submittedPrice)||submittedPrice<=0))throw fail('Add a valid daily rental price.');if(submittedPrice!==null&&(!Number.isFinite(submittedPrice)||submittedPrice<0))throw fail('Rental price must be zero or more.');const price=type==='borrow'?null:submittedPrice;if((available_from&&!validISODate(available_from))||(available_until&&!validISODate(available_until)))throw fail('Choose valid availability dates.');if(available_from&&available_until&&available_until<available_from)throw fail('The availability end date must be after its start date.');const validImage=typeof image_url==='string'&&(/^https:\/\//i.test(image_url)||/^data:image\/(jpeg|png|webp);base64,[a-z0-9+/]+=*$/i.test(image_url)&&image_url.length<=850000);if(image_url&&!validImage)throw fail('Choose a valid HTTPS image or a JPG, PNG, or WebP image smaller than 600 KB.');const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('INSERT INTO items(owner_id,category_id,title,description,condition,type,location,price_per_day,available_from,available_until) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id',[req.user.id,category_id||null,title.trim(),description.trim(),condition,type,location||null,price,available_from||null,available_until||null]);if(image_url)await client.query('INSERT INTO item_images(item_id,image_url) VALUES($1,$2)',[rows[0].id,image_url]);await client.query('COMMIT');res.status(201).json({id:rows[0].id});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.patch('/items/:id',auth,asyncRoute(async(req,res)=>{const {title,description,condition,type,location,status}=req.body||{};if(title!==undefined&&(typeof title!=='string'||title.trim().length<2||title.trim().length>160))throw fail('Item title must be between 2 and 160 characters.');if(description!==undefined&&(typeof description!=='string'||description.trim().length<5||description.trim().length>5000))throw fail('Description must be between 5 and 5,000 characters.');if(condition!==undefined&&!['new','like_new','good','used'].includes(condition))throw fail('Choose a valid condition.');if(type!==undefined&&!['lend','donate','exchange','borrow','rent','both'].includes(type))throw fail('Choose a valid sharing type.');if(location!==undefined&&(typeof location!=='string'||location.length>160))throw fail('Location must be 160 characters or fewer.');if(status!==undefined&&!['available','unavailable'].includes(status))throw fail('Listings can only be marked available or unavailable.');const {rows}=await pool.query(`UPDATE items SET title=COALESCE($1,title),description=COALESCE($2,description),condition=COALESCE($3,condition),type=COALESCE($4,type),location=COALESCE($5,location),status=COALESCE($6,status),updated_at=NOW() WHERE id=$7 AND owner_id=$8 AND (status<>'shared' OR $6 IS NULL) RETURNING id`,[title?.trim()||null,description?.trim()||null,condition||null,type||null,location??null,status||null,req.params.id,req.user.id]);if(!rows[0])throw fail('Item not found, unavailable, or it is currently being shared.',409);res.json({success:true});}));
router.delete('/items/:id',auth,asyncRoute(async(req,res)=>{if(!validUUID(req.params.id))throw fail('Item not found.',404);const owned=await pool.query('SELECT id FROM items WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.id]);if(!owned.rowCount)throw fail('Item not found or you do not own it.',404);const history=await pool.query('SELECT EXISTS(SELECT 1 FROM requests WHERE item_id=$1) OR EXISTS(SELECT 1 FROM transactions WHERE item_id=$1) OR EXISTS(SELECT 1 FROM item_inquiries WHERE item_id=$1) AS has_history',[req.params.id]);if(history.rows[0].has_history)throw fail('This listing has request or message history and cannot be deleted. Mark it unavailable instead.',409);await pool.query('DELETE FROM items WHERE id=$1 AND owner_id=$2',[req.params.id,req.user.id]);res.status(204).end();}));router.get('/items/mine/list',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT ${itemFields} FROM items i JOIN users u ON u.id=i.owner_id LEFT JOIN categories c ON c.id=i.category_id WHERE i.owner_id=$1 ORDER BY i.created_at DESC`,[req.user.id]);res.json(rows);}));
router.post('/requests',auth,asyncRoute(async(req,res)=>{const {item_id,message='',request_type='borrow',start_date,end_date}=req.body||{};const note=typeof message==='string'?message.trim():'';if(!item_id||note.length>1000||(note&&note.length<5))throw fail('Keep your optional note between 5 and 1,000 characters.');if(!['borrow','rent','donate','exchange'].includes(request_type))throw fail('Choose a valid borrowing, rental, donation, or exchange request.');if(!validISODate(start_date)||!validISODate(end_date)||end_date<start_date||start_date<new Date().toISOString().slice(0,10))throw fail('Choose a valid sharing start and end date.');const client=await pool.connect();try{await client.query('BEGIN');const item=await client.query("SELECT id,owner_id,type,price_per_day,available_from,available_until FROM items WHERE id=$1 AND status='available' FOR UPDATE",[item_id]);const available=item.rows[0];if(!available)throw fail('This item is no longer available.',409);if(available.owner_id===req.user.id)throw fail('You cannot request your own item.');if(request_type==='rent'&&!['rent','both'].includes(available.type))throw fail('This item is not available to rent.',409);if(request_type==='borrow'&&!['lend','borrow','both'].includes(available.type))throw fail('This item is not available to borrow.',409);if(request_type==='donate'&&available.type!=='donate')throw fail('This item is not offered for donation.',409);if(request_type==='exchange'&&available.type!=='exchange')throw fail('This item is not offered for exchange.',409);if(request_type==='rent'&&Number(available.price_per_day||0)<=0)throw fail('The owner has not set a rental price for this item.',409);if(available.available_from&&start_date<String(available.available_from).slice(0,10))throw fail('The requested dates are outside the owner’s availability.',409);if(available.available_until&&end_date>String(available.available_until).slice(0,10))throw fail('The requested dates are outside the owner’s availability.',409);const {rows}=await client.query('INSERT INTO requests(item_id,requester_id,owner_id,message,request_type,start_date,end_date) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id',[item_id,req.user.id,available.owner_id,note||'I would like to request this item.',request_type,start_date,end_date]);await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'request','New item request',$2)",[available.owner_id,`${req.user.name} requested your item.`]);await client.query('COMMIT');res.status(201).json({id:rows[0].id});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.get('/requests',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT r.*,i.title,item_owner.name AS owner_name,requester.name AS requester_name FROM requests r JOIN items i ON i.id=r.item_id JOIN users item_owner ON item_owner.id=r.owner_id JOIN users requester ON requester.id=r.requester_id WHERE r.owner_id=$1 OR r.requester_id=$1 ORDER BY r.requested_at DESC`,[req.user.id]);res.json(rows);}));
router.patch('/requests/:id',auth,asyncRoute(async(req,res)=>{
  const {status}=req.body||{};
  if(!['accepted','rejected','cancelled'].includes(status))throw fail('Choose accepted, rejected, or cancelled.');
  const client=await pool.connect();
  try{
    await client.query('BEGIN');
    const peek=await client.query('SELECT * FROM requests WHERE id=$1',[req.params.id]);
    const initial=peek.rows[0];
    if(!initial)throw fail('Request not found.',404);
    if((status==='accepted'||status==='rejected')&&initial.owner_id!==req.user.id)throw fail('Only the item owner can respond.',403);
    if(status==='cancelled'&&initial.requester_id!==req.user.id)throw fail('Only the requester can cancel.',403);
    let item;
    if(status==='accepted'){
      const lockedItem=await client.query('SELECT status,price_per_day,available_from,available_until FROM items WHERE id=$1 FOR UPDATE',[initial.item_id]);
      item=lockedItem.rows[0];
      if(!item||item.status!=='available')throw fail('This item has already been reserved.',409);
      if(initial.start_date&&item.available_from&&String(item.available_from).slice(0,10)>initial.start_date)throw fail('The requested dates are outside the owner availability.',409);
      if(initial.end_date&&item.available_until&&String(item.available_until).slice(0,10)<initial.end_date)throw fail('The requested dates are outside the owner availability.',409);
    }
    const locked=await client.query('SELECT * FROM requests WHERE id=$1 FOR UPDATE',[req.params.id]);
    const request=locked.rows[0];
    if(!request||request.status!=='pending')throw fail('This request has already been resolved.',409);
    await client.query('UPDATE requests SET status=$1,responded_at=NOW() WHERE id=$2',[status,request.id]);
    if(status==='accepted'){
      const startDate=request.start_date||new Date().toISOString().slice(0,10);
      const days=request.start_date&&request.end_date?Math.max(1,Math.ceil((new Date(`${request.end_date}T00:00:00Z`)-new Date(`${request.start_date}T00:00:00Z`))/86400000)+1):1;
      const price=request.request_type==='rent'?Number(item.price_per_day||0):0;
      await client.query("UPDATE items SET status='shared',updated_at=NOW() WHERE id=$1",[request.item_id]);
      await client.query('INSERT INTO transactions(item_id,owner_id,borrower_id,request_id,start_date,expected_return_date,request_type,price_per_day,total_price) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[request.item_id,request.owner_id,request.requester_id,request.id,startDate,request.end_date||null,request.request_type,price,price*days]);
      const rejected=await client.query("UPDATE requests SET status='rejected',responded_at=NOW() WHERE item_id=$1 AND id<>$2 AND status='pending' RETURNING requester_id",[request.item_id,request.id]);
      for(const declined of rejected.rows)await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'request_update','Request closed','Another request for this item was accepted.')",[declined.requester_id]);
      await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'request_update','Request approved',$2)",[request.requester_id,`Your ${request.request_type} request was approved. The share is now active.`]);
      await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'transaction_started','Share started','You accepted a sharing request. Coordinate the handoff with the requester.')",[request.owner_id]);
    }else{
      const recipient=status==='cancelled'?request.owner_id:request.requester_id;
      await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'request_update','Request updated',$2)",[recipient,status==='rejected'?`Your ${request.request_type} request was rejected.`:`Your request was ${status}.`]);
    }
    await client.query('COMMIT');res.json({success:true,status});
  }catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}
}));
router.get('/transactions',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT t.*,i.title,owner.name AS owner_name,borrower.name AS borrower_name FROM transactions t JOIN items i ON i.id=t.item_id JOIN users owner ON owner.id=t.owner_id JOIN users borrower ON borrower.id=t.borrower_id WHERE t.owner_id=$1 OR t.borrower_id=$1 ORDER BY t.started_at DESC`,[req.user.id]);res.json(rows);}));
router.patch('/transactions/:id/return',auth,asyncRoute(async(req,res)=>{const client=await pool.connect();try{await client.query('BEGIN');const {rows}=await client.query('SELECT * FROM transactions WHERE id=$1 FOR UPDATE',[req.params.id]);const t=rows[0];if(!t)throw fail('Transaction not found.',404);const isOwner=t.owner_id===req.user.id;if(!isOwner&&t.borrower_id!==req.user.id)throw fail('Access denied.',403);if(t.status!=='active')throw fail('Transaction is already closed.',409);const ownColumn=isOwner?'owner_return_confirmed_at':'borrower_return_confirmed_at';await client.query(`UPDATE transactions SET ${ownColumn}=COALESCE(${ownColumn},NOW()) WHERE id=$1`,[t.id]);const ownerConfirmed=Boolean(t.owner_return_confirmed_at)||isOwner;const borrowerConfirmed=Boolean(t.borrower_return_confirmed_at)||!isOwner;const completed=ownerConfirmed&&borrowerConfirmed;if(completed){await client.query("UPDATE transactions SET status='completed',returned_at=NOW() WHERE id=$1",[t.id]);await client.query("UPDATE items SET status=CASE WHEN available_until IS NOT NULL AND available_until < CURRENT_DATE THEN 'unavailable' ELSE 'available' END,updated_at=NOW() WHERE id=$1",[t.item_id]);for(const recipient of [t.owner_id,t.borrower_id])await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'transaction_completed','Share completed','Both students confirmed the return. You can now leave a review.')",[recipient]);}else{const recipient=isOwner?t.borrower_id:t.owner_id;await client.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'return_confirmation','Return confirmation needed',$2)",[recipient,`${req.user.name} confirmed the item return. Please confirm to complete the share.`]);}await client.query('COMMIT');res.json({success:true,status:completed?'completed':'active',owner_return_confirmed:ownerConfirmed,borrower_return_confirmed:borrowerConfirmed});}catch(e){await client.query('ROLLBACK');throw e;}finally{client.release();}}));
router.get('/notifications',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT * FROM notifications WHERE user_id=$1 ORDER BY created_at DESC LIMIT 50',[req.user.id]);res.json(rows);}));
router.patch('/notifications/read',auth,asyncRoute(async(req,res)=>{await pool.query('UPDATE notifications SET is_read=true WHERE user_id=$1',[req.user.id]);res.json({success:true});}));
router.get('/impact',asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT (SELECT COUNT(DISTINCT item_id)::int FROM transactions WHERE status IN ('completed','returned')) AS items_reused,(SELECT COUNT(DISTINCT person)::int FROM (SELECT owner_id AS person FROM transactions WHERE status IN ('completed','returned') UNION SELECT borrower_id FROM transactions WHERE status IN ('completed','returned')) people) AS students_helped,(SELECT COUNT(*)::int FROM transactions WHERE status IN ('completed','returned')) AS completed_shares,(SELECT COUNT(*)::int FROM items WHERE status='available') AS available_items`);res.json(rows[0]);}));
router.get('/profiles/:id',asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT u.id,u.name,u.college,u.department,u.year,u.created_at,COALESCE((SELECT AVG(rating)::numeric(3,2) FROM reviews WHERE reviewee_id=u.id),0) AS average_rating,COALESCE((SELECT COUNT(*)::int FROM reviews WHERE reviewee_id=u.id),0) AS review_count,COALESCE((SELECT COUNT(*)::int FROM items WHERE owner_id=u.id),0) AS items_shared,COALESCE((SELECT COUNT(*)::int FROM transactions WHERE borrower_id=u.id AND status IN ('completed','returned')),0) AS shares_borrowed,COALESCE((SELECT COUNT(*)::int FROM transactions WHERE (owner_id=u.id OR borrower_id=u.id) AND status IN ('completed','returned')),0) AS completed_transactions FROM users u WHERE u.id=$1 AND u.status='active'`,[req.params.id]);if(!rows[0])throw fail('Profile not found.',404);res.json(rows[0]);}));
router.get('/profiles/:id/reviews',asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT r.rating,r.body,r.created_at,u.name AS reviewer_name FROM reviews r JOIN users u ON u.id=r.reviewer_id WHERE r.reviewee_id=$1 ORDER BY r.created_at DESC LIMIT 50',[req.params.id]);res.json(rows);}));
router.get('/requests/:id/messages',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT id,requester_id,owner_id FROM requests WHERE id=$1 AND (requester_id=$2 OR owner_id=$2)',[req.params.id,req.user.id]);const request=rows[0];if(!request)throw fail('Conversation not found.',404);await pool.query('UPDATE messages SET read_at=NOW() WHERE request_id=$1 AND recipient_id=$2 AND read_at IS NULL',[req.params.id,req.user.id]);const messages=await pool.query('SELECT id,sender_id,recipient_id,body,created_at,read_at FROM messages WHERE request_id=$1 ORDER BY created_at',[req.params.id]);res.json(messages.rows);}));
router.post('/requests/:id/messages',auth,asyncRoute(async(req,res)=>{const body=typeof req.body?.body==='string'?req.body.body.trim():'';if(body.length<1||body.length>2000)throw fail('Message must be between 1 and 2,000 characters.');const {rows}=await pool.query('SELECT requester_id,owner_id FROM requests WHERE id=$1 AND (requester_id=$2 OR owner_id=$2)',[req.params.id,req.user.id]);const request=rows[0];if(!request)throw fail('Conversation not found.',404);const recipient=request.requester_id===req.user.id?request.owner_id:request.requester_id;const result=await pool.query('INSERT INTO messages(request_id,sender_id,recipient_id,body) VALUES($1,$2,$3,$4) RETURNING id,sender_id,recipient_id,body,created_at',[req.params.id,req.user.id,recipient,body]);await pool.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'message','New message',$2)",[recipient,`${req.user.name} sent you a message.`]);res.status(201).json(result.rows[0]);}));
router.get('/inquiries',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT q.id,q.item_id,q.created_at,i.title,CASE WHEN q.requester_id=$1 THEN owner.name ELSE requester.name END AS other_person,CASE WHEN q.requester_id=$1 THEN q.owner_id ELSE q.requester_id END AS other_user_id,(SELECT body FROM messages WHERE inquiry_id=q.id ORDER BY created_at DESC LIMIT 1) AS last_message,(SELECT created_at FROM messages WHERE inquiry_id=q.id ORDER BY created_at DESC LIMIT 1) AS last_message_at FROM item_inquiries q JOIN items i ON i.id=q.item_id JOIN users owner ON owner.id=q.owner_id JOIN users requester ON requester.id=q.requester_id WHERE q.owner_id=$1 OR q.requester_id=$1 ORDER BY COALESCE((SELECT created_at FROM messages WHERE inquiry_id=q.id ORDER BY created_at DESC LIMIT 1),q.created_at) DESC`,[req.user.id]);res.json(rows);}));
router.get('/inquiries/:id/messages',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT id,requester_id,owner_id FROM item_inquiries WHERE id=$1 AND (requester_id=$2 OR owner_id=$2)',[req.params.id,req.user.id]);if(!rows[0])throw fail('Conversation not found.',404);await pool.query('UPDATE messages SET read_at=NOW() WHERE inquiry_id=$1 AND recipient_id=$2 AND read_at IS NULL',[req.params.id,req.user.id]);const messages=await pool.query('SELECT id,sender_id,recipient_id,body,created_at,read_at FROM messages WHERE inquiry_id=$1 ORDER BY created_at',[req.params.id]);res.json(messages.rows);}));
router.post('/inquiries/:id/messages',auth,asyncRoute(async(req,res)=>{const body=typeof req.body?.body==='string'?req.body.body.trim():'';if(body.length<1||body.length>2000)throw fail('Message must be between 1 and 2,000 characters.');const {rows}=await pool.query('SELECT requester_id,owner_id FROM item_inquiries WHERE id=$1 AND (requester_id=$2 OR owner_id=$2)',[req.params.id,req.user.id]);const inquiry=rows[0];if(!inquiry)throw fail('Conversation not found.',404);const recipient=inquiry.requester_id===req.user.id?inquiry.owner_id:inquiry.requester_id;const result=await pool.query('INSERT INTO messages(inquiry_id,sender_id,recipient_id,body) VALUES($1,$2,$3,$4) RETURNING id,sender_id,recipient_id,body,created_at',[req.params.id,req.user.id,recipient,body]);await pool.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'message','New item message',$2)",[recipient,`${req.user.name} sent you a CampusShare message.`]);res.status(201).json(result.rows[0]);}));
router.get('/transactions/:id/reviews',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query('SELECT * FROM transactions WHERE id=$1 AND (owner_id=$2 OR borrower_id=$2)',[req.params.id,req.user.id]);if(!rows[0])throw fail('Transaction not found.',404);const result=await pool.query('SELECT r.id,r.transaction_id,r.reviewer_id,r.reviewee_id,r.rating,r.body,r.created_at,u.name AS reviewer_name FROM reviews r JOIN users u ON u.id=r.reviewer_id WHERE r.transaction_id=$1 ORDER BY r.created_at',[req.params.id]);res.json(result.rows);}));
router.post('/transactions/:id/reviews',auth,asyncRoute(async(req,res)=>{const rating=Number(req.body?.rating),body=typeof req.body?.body==='string'?req.body.body.trim():'';if(!Number.isInteger(rating)||rating<1||rating>5||body.length>1000)throw fail('Choose a 1–5 star rating and keep the review under 1,000 characters.');const {rows}=await pool.query("SELECT * FROM transactions WHERE id=$1 AND status IN ('completed','returned') AND (owner_id=$2 OR borrower_id=$2)",[req.params.id,req.user.id]);const transaction=rows[0];if(!transaction)throw fail('A review is available after a completed share.',409);const reviewee=transaction.owner_id===req.user.id?transaction.borrower_id:transaction.owner_id;const exists=await pool.query('SELECT 1 FROM reviews WHERE transaction_id=$1 AND reviewer_id=$2',[req.params.id,req.user.id]);if(exists.rowCount)throw fail('You already reviewed this share.',409);const result=await pool.query('INSERT INTO reviews(transaction_id,reviewer_id,reviewee_id,rating,body) VALUES($1,$2,$3,$4,$5) RETURNING id',[req.params.id,req.user.id,reviewee,rating,body||null]);await pool.query("INSERT INTO notifications(user_id,type,title,message) VALUES($1,'review','New review','A student left you a review.')",[reviewee]);res.status(201).json({id:result.rows[0].id});}));
router.post('/reports',auth,asyncRoute(async(req,res)=>{const {reported_user_id,reported_item_id,reason,description}=req.body||{};if(typeof reason!=='string'||reason.trim().length<3||reason.length>120)throw fail('Provide a reason for this report.');const {rows}=await pool.query('INSERT INTO reports(reporter_id,reported_user_id,reported_item_id,reason,description) VALUES($1,$2,$3,$4,$5) RETURNING id',[req.user.id,reported_user_id||null,reported_item_id||null,reason.trim(),(description||'').slice(0,2000)]);res.status(201).json({id:rows[0].id});}));
router.get('/admin/reports',auth,admin,asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT r.*,u.name AS reporter_name FROM reports r JOIN users u ON u.id=r.reporter_id ORDER BY r.created_at DESC');res.json(rows);}));
router.patch('/admin/reports/:id',auth,admin,asyncRoute(async(req,res)=>{const {status}=req.body||{};if(!['reviewing','resolved','dismissed','open'].includes(status))throw fail('Invalid report status.');const {rowCount}=await pool.query('UPDATE reports SET status=$1,resolved_at=CASE WHEN $1 IN (\'resolved\',\'dismissed\') THEN NOW() ELSE NULL END WHERE id=$2',[status,req.params.id]);if(!rowCount)throw fail('Report not found.',404);res.json({success:true});}));
router.get('/admin/users',auth,admin,asyncRoute(async(_req,res)=>{const {rows}=await pool.query('SELECT id,name,email,college,role,status,created_at FROM users ORDER BY created_at DESC LIMIT 500');res.json(rows);}));
router.patch('/admin/users/:id/status',auth,admin,asyncRoute(async(req,res)=>{const {status}=req.body||{};if(!['active','suspended'].includes(status))throw fail('Invalid account status.');if(req.params.id===req.user.id&&status==='suspended')throw fail('You cannot suspend your own account.');const {rowCount}=await pool.query('UPDATE users SET status=$1,updated_at=NOW() WHERE id=$2',[status,req.params.id]);if(!rowCount)throw fail('User not found.',404);res.json({success:true});}));
module.exports=router;
